name: 新機能の提案
description: このソフトウェアに是非追加してほしい機能をご提案ください！
title: "[FEAT]: "
labels: [ "enhancement", "need-triage" ]
assignees: [ "hizumiaoba" ]
body:
  - type: markdown
    attributes:
      value: |
        この度は新機能提案にご協力いただき、ありがとうございます。以下の情報をご記入ください。
  - type: input
    id: contact
    attributes:
      label: 連絡先
      description: さらに追加の連絡を必要とする場合は、こちらに連絡先情報をご記入ください。
      placeholder: 連絡先をご記入ください。
    validations:
      required: false
  - type: textarea
    id: description
    attributes:
      label: 提案する機能の詳細
      description: 提案する機能の詳細をご記入ください。
      placeholder: 提案する機能の詳細をご記入ください。
    validations:
      required: true
  - type: textarea
    id: objective
    attributes:
      label: 提案する機能が必要と感じる目的をご記入ください。
      description: 提案する機能が必要と感じる目的をご記入ください。
      placeholder: 提案する機能が必要と感じる目的をご記入ください。
    validations:
      required: true
